import { saveAs } from "file-saver";
import * as XLSX from "xlsx";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// =========================
// EXPORT CSV
// =========================
export const exportCSV = (data) => {

  if (!data.length) {

    alert(
      "No dataset available for CSV export."
    );

    return;
  }

  const worksheet =
    XLSX.utils.json_to_sheet(data);

  const csv =
    XLSX.utils.sheet_to_csv(
      worksheet
    );

  const blob = new Blob(
    [csv],
    {
      type:
        "text/csv;charset=utf-8;",
    }
  );

  saveAs(
    blob,
    "enterprise_dataset_export.csv"
  );
};

// =========================
// EXPORT EXCEL
// =========================
export const exportExcel = (data) => {

  if (!data.length) {

    alert(
      "No dataset available for Excel export."
    );

    return;
  }

  const worksheet =
    XLSX.utils.json_to_sheet(data);

  // AUTO COLUMN WIDTHS
  const columnWidths =
    Object.keys(data[0]).map(
      (key) => ({
        wch: Math.max(
          key.length,
          20
        ),
      })
    );

  worksheet["!cols"] =
    columnWidths;

  const workbook =
    XLSX.utils.book_new();

  XLSX.utils.book_append_sheet(
    workbook,
    worksheet,
    "Healthcare Analytics"
  );

  XLSX.writeFile(
    workbook,
    "enterprise_healthcare_report.xlsx"
  );
};

// =========================
// EXPORT PDF
// =========================
export const exportPDF = (
  data,
  insights
) => {

  const doc = new jsPDF();

  // =========================
  // HEADER
  // =========================
  doc.setFillColor(
    15,
    23,
    42
  );

  doc.rect(
    0,
    0,
    220,
    35,
    "F"
  );

  doc.setTextColor(
    255,
    255,
    255
  );

  doc.setFontSize(24);

  doc.text(
    "InsightFlow AI",
    14,
    20
  );

  doc.setFontSize(11);

  doc.text(
    "Enterprise Healthcare Analytics Platform",
    14,
    28
  );

  // =========================
  // REPORT INFO
  // =========================
  doc.setTextColor(
    0,
    0,
    0
  );

  doc.setFontSize(12);

  doc.text(
    `Generated: ${new Date().toLocaleString()}`,
    14,
    48
  );

  doc.text(
    `Total Records: ${data.length}`,
    14,
    58
  );

  // =========================
  // INSIGHTS SECTION
  // =========================
  doc.setFontSize(16);

  doc.text(
    "AI Generated Insights",
    14,
    78
  );

  doc.setFontSize(11);

  insights.forEach(
    (item, index) => {

      doc.text(
        `• ${item}`,
        20,
        90 + index * 10
      );

    }
  );

  // =========================
  // TABLE
  // =========================
  if (data.length > 0) {

    autoTable(doc, {

      startY:
        100 +
        insights.length * 10,

      head: [
        Object.keys(data[0]),
      ],

      body: data
        .slice(0, 15)
        .map((row) =>
          Object.values(row)
        ),

      styles: {

        fillColor: [
          255,
          255,
          255,
        ],

        textColor: 20,

        fontSize: 8,
      },

      headStyles: {

        fillColor: [
          34,
          211,
          238,
        ],

        textColor: 0,
      },

    });
  }

  // =========================
  // FOOTER
  // =========================
  doc.setFontSize(10);

  doc.setTextColor(
    120
  );

  doc.text(
    "Generated by InsightFlow AI • Enterprise Analytics Suite",
    14,
    285
  );

  // =========================
  // SAVE PDF
  // =========================
  doc.save(
    "InsightFlow_Executive_Report.pdf"
  );
};